#ifndef __CONSTANTS
#define __CONSTANTS

#define EXIT_SYSTEM_SUCCESS 0
#define EXIT_SYSTEM_ERROR 1

#define EXIT_JUDGE_AC 128
#define EXIT_JUDGE_MLE 129
#define EXIT_JUDGE_TLE 130
#define EXIT_JUDGE_RE 131
#define EXIT_JUDGE_CE 132
#define EXIT_JUDGE_WA 133

#define MB_TO_BYTES 1 * 1024 * 1024
#define MB_TO_KB 1024
#define KB_TO_BYTES 1024

// some magic number
#define EXEC_ERROR_EXIT_CODE 123
#define SPJ_TIME_OUT 20
#define COMPILE_TIME_OUT 5
#define COMPILE_RLIMIT_FSIZE 64 * MB_TO_BYTES

#endif